// Copyright (c) 2026, Arm Limited and contributors.
// SPDX-License-Identifier: Apache-2.0
//
// S32Z2 board bring-up: RTD init, UART9 console, newlib _write retarget.

#include <stdint.h>
#include <unistd.h>
#include <errno.h>

#include "platform/freertos/s32z2/board_init.h"

#include "Clock_Ip.h"
#include "Siul2_Port_Ip.h"
#include "Linflexd_Uart_Ip.h"
#include "Linflexd_Uart_Ip_VS_0_PBcfg.h"

// S32CT-generated pin-mux table. NUM_OF_CONFIGURED_PINS comes from the board
// Siul2_Port_Ip_Cfg.h; g_pin_mux_InitConfigArr_VS_0 (the actual pad settings)
// from the generated PB cfg. This table muxes the NETC ETH0 RGMII pins
// (SIUL2_1[58..65] -> ALT1 = ETH_0_RGMII_TXD/RXD/TXC/TXCTL/RXCTL/RX_CLK) plus
// the PHY GPIO control pins. The lwip example applies it via Port_Init(); we
// apply it directly with Siul2_Port_Ip_Init() (see board_init()).
#include "Siul2_Port_Ip_Cfg.h"
#include "Siul2_Port_Ip_VS_0_PBcfg.h"

// AUTOSAR Mcu_Init / Port_Init / Platform_Init would require Mcu_Cfg.c /
// Port_Cfg.c / Platform_Cfg.c — those PB configs are absent from the lwip
// S32CT example (Components view does not instantiate them), so the build
// filters them out. The NXP startup.s + SystemInit handle MCU bring-up
// before main(); we still need the IP-layer Clock_Ip_Init below to enable
// the LINFLEXD9 module clock that SystemInit does not touch.

// Mcu_aClockConfigPB[] is defined in Clock_Ip_VS_0_PBcfg.c (S32CT
// generated). The lwip example uses the AUTOSAR-Mcu naming
// (Mcu_aClockConfigPB) rather than the bare Clock_Ip_aClockConfig from
// non-AUTOSAR examples — both are the same Clock_Ip_ClockConfigType
// array. Element 0 is the default ClockConfig0 that turns the LINFLEXD9
// module clock on.
extern const Clock_Ip_ClockConfigType Mcu_aClockConfigPB[];

// LINFLEXD instance 9 is wired to the X-S32Z27X-DC FT232RQ console
// (matches the Zephyr `_D` overlay's `zephyr,console = &uart9`).
// PB cfg symbol is generated by S32CT into Linflexd_Uart_Ip_VS_0_PBcfg.c.
extern const Linflexd_Uart_Ip_UserConfigType Linflexd_Uart_Ip_xHwConfigPB_0_VS_0;

// SIUL2_5 PORT150 → ALT1 → LIN_9_TX. The S32CT Pins tool added the routing
// to the .mex but the Update Code action did not regenerate the Siul2_Port
// PB cfg, so we configure the pad inline via the RTD IP-layer API.
static const Siul2_Port_Ip_PinSettingsConfig kLin9TxPin = {
    .base                     = IP_SIUL2_5,
    .pinPortIdx               = 150U,
    .mux                      = PORT_MUX_ALT1,
    .safeMode                 = PORT_SAFE_MODE_DISABLED,
    .pullConfig               = PORT_INTERNAL_PULL_NOT_ENABLED,
    .slewRateCtrlSel          = PORT_SLEW_RATE_CONTROL0,
    .receiverSel              = PORT_RECEIVER_NOT_AVAILABLE,
    .terminationResistor      = PORT_TERMINATION_RESISTOR_NOT_AVAILABLE,
    .currentReferenceControl  = PORT_CURRENT_REFERENCE_CONTROL_NOT_AVAILABLE,
    .rxCurrentBoost           = PORT_RX_CURRENT_BOOST_NOT_AVAILABLE,
    .openDrain                = PORT_OPEN_DRAIN_DISABLED,
    .inputBuffer              = PORT_INPUT_BUFFER_DISABLED,
    .outputBuffer             = PORT_OUTPUT_BUFFER_ENABLED,
    .initValue                = 0U,
    .inputMuxReg              = { 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U },
    .inputMux                 = { 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U },
};

void uart9_init_115200_8N1(void) {
    Siul2_Port_Ip_PinInit(&kLin9TxPin);
    (void)Linflexd_Uart_Ip_Init(9U, &Linflexd_Uart_Ip_xHwConfigPB_0_VS_0);
}

int uart9_tx_byte(uint8_t b) {
    return (Linflexd_Uart_Ip_SyncSend(9U, &b, 1U, 100U)
            == LINFLEXD_UART_IP_STATUS_SUCCESS) ? 0 : -1;
}

int board_init(void) {
    (void)Clock_Ip_Init(&Mcu_aClockConfigPB[0U]);
    uart9_init_115200_8N1();
    // Mux the NETC ETH0 RGMII + PHY-control pins. Without this the MAC<->PHY
    // RGMII pins stay at their reset function and the Ethernet wire interface is
    // dead in BOTH directions (no TX on the wire, no RX) -- the lwip example
    // does this inside Port_Init(), which the board otherwise skips.
    (void)Siul2_Port_Ip_Init(NUM_OF_CONFIGURED_PINS, g_pin_mux_InitConfigArr_VS_0);
    return 0;
}

// generic_timer.c registers SysTick_Handler as the physical-timer ISR but
// leaves it up to the application. We alias it to the CR52 port's
// xPortSysTickHandler via a linker --defsym in CMakeLists.txt.

// Newlib retarget: every printf/puts/fwrite to stdout/stderr ends up here.
int _write(int fd, const char *buf, int len) {
    if (fd != 1 && fd != 2) {
        errno = EBADF;
        return -1;
    }
    for (int i = 0; i < len; ++i) {
        if (uart9_tx_byte((uint8_t)buf[i]) != 0) {
            return i;
        }
    }
    return len;
}

// Newlib stubs to keep the link clean for bare metal.
int _close(int fd) { (void)fd; errno = EBADF; return -1; }
int _lseek(int fd, int off, int whence) { (void)fd; (void)off; (void)whence; errno = EBADF; return -1; }
int _read(int fd, char *buf, int len) { (void)fd; (void)buf; (void)len; errno = EBADF; return -1; }
int _fstat(int fd, void *st) { (void)fd; (void)st; errno = EBADF; return -1; }
int _isatty(int fd) { return (fd == 1 || fd == 2) ? 1 : 0; }
int _getpid(void) { return 1; }
int _kill(int pid, int sig) { (void)pid; (void)sig; errno = EINVAL; return -1; }

// ---- PIT-driven FreeRTOS tick ----
// Engineer substitutes the actual PIT register layout from the S32Z2
// reference manual; the RTD typically exposes Pit_Ip_Init / Pit_Ip_StartChannel.
// PIT channel 0, period = configCPU_CLOCK_HZ / configTICK_RATE_HZ.

#include "FreeRTOSConfig.h"

extern void Pit_Ip_Init(void);
extern void Pit_Ip_StartChannel(uint8_t instance, uint8_t channel, uint32_t ticks);
extern void Pit_Ip_ClearInterruptFlag(uint8_t instance, uint8_t channel);

void s32z2_pit_setup_tick_interrupt(void) {
    Pit_Ip_Init();
    Pit_Ip_StartChannel(0u, 0u,
        (uint32_t)(configCPU_CLOCK_HZ / configTICK_RATE_HZ));
}

void s32z2_pit_clear_tick_interrupt(void) {
    Pit_Ip_ClearInterruptFlag(0u, 0u);
}
